name: flutter_multistore_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7

  freezed_annotation: ^2.4.1
  http: ^1.1.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  money_formatter: ^0.0.5
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
